<?php

namespace Database\Seeders;

use App\Models\Job;
use App\Models\User;
use App\Models\EmployerProfile;
use Illuminate\Database\Seeder;

class CompaniesAndJobsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Canadian cities for job locations
        $cities = [
            'Toronto, ON', 'Vancouver, BC', 'Calgary, AB', 'Ottawa, ON', 'Montreal, QC',
            'Edmonton, AB', 'Winnipeg, MB', 'Hamilton, ON', 'Quebec City, QC', 'Mississauga, ON'
        ];

        // Define 10 companies with their details
        $companies = [
            [
                'name' => 'Metro Clean Services',
                'email' => 'metro.clean@example.com',
                'business_name' => 'Metro Clean Services',
                'phone' => '416-555-0101',
                'city' => 'Toronto',
                'province' => 'ON',
                'address_line_1' => '123 Main Street',
                'postal_code' => 'M5H 2N2',
            ],
            [
                'name' => 'Quick Bite Restaurant Group',
                'email' => 'quickbite@example.com',
                'business_name' => 'Quick Bite Restaurant Group',
                'phone' => '604-555-0202',
                'city' => 'Vancouver',
                'province' => 'BC',
                'address_line_1' => '456 Granville Street',
                'postal_code' => 'V6C 1V6',
            ],
            [
                'name' => 'City Express Delivery',
                'email' => 'cityexpress@example.com',
                'business_name' => 'City Express Delivery',
                'phone' => '403-555-0303',
                'city' => 'Calgary',
                'province' => 'AB',
                'address_line_1' => '789 8th Avenue SW',
                'postal_code' => 'T2P 1H9',
            ],
            [
                'name' => 'Retail Plus Stores',
                'email' => 'retailplus@example.com',
                'business_name' => 'Retail Plus Stores',
                'phone' => '613-555-0404',
                'city' => 'Ottawa',
                'province' => 'ON',
                'address_line_1' => '321 Bank Street',
                'postal_code' => 'K1P 1N7',
            ],
            [
                'name' => 'Fresh Market Grocers',
                'email' => 'freshmarket@example.com',
                'business_name' => 'Fresh Market Grocers',
                'phone' => '514-555-0505',
                'city' => 'Montreal',
                'province' => 'QC',
                'address_line_1' => '654 Rue Sainte-Catherine',
                'postal_code' => 'H3B 1B1',
            ],
            [
                'name' => 'Elite Event Services',
                'email' => 'eliteevents@example.com',
                'business_name' => 'Elite Event Services',
                'phone' => '780-555-0606',
                'city' => 'Edmonton',
                'province' => 'AB',
                'address_line_1' => '987 Jasper Avenue',
                'postal_code' => 'T5J 1Y9',
            ],
            [
                'name' => 'Comfort Home Care',
                'email' => 'comforthome@example.com',
                'business_name' => 'Comfort Home Care',
                'phone' => '204-555-0707',
                'city' => 'Winnipeg',
                'province' => 'MB',
                'address_line_1' => '147 Portage Avenue',
                'postal_code' => 'R3B 2B4',
            ],
            [
                'name' => 'Green Lawn Landscaping',
                'email' => 'greenlawn@example.com',
                'business_name' => 'Green Lawn Landscaping',
                'phone' => '905-555-0808',
                'city' => 'Hamilton',
                'province' => 'ON',
                'address_line_1' => '258 King Street West',
                'postal_code' => 'L8P 1A1',
            ],
            [
                'name' => 'Speedy Courier Services',
                'email' => 'speedycourier@example.com',
                'business_name' => 'Speedy Courier Services',
                'phone' => '418-555-0909',
                'city' => 'Quebec City',
                'province' => 'QC',
                'address_line_1' => '369 Rue Saint-Jean',
                'postal_code' => 'G1R 1P3',
            ],
            [
                'name' => 'Warehouse Logistics Inc',
                'email' => 'warehouselog@example.com',
                'business_name' => 'Warehouse Logistics Inc',
                'phone' => '905-555-1010',
                'city' => 'Mississauga',
                'province' => 'ON',
                'address_line_1' => '741 Hurontario Street',
                'postal_code' => 'L5B 1M8',
            ],
        ];

        $employers = [];

        // Create employer users and profiles
        foreach ($companies as $company) {
            $user = User::create([
                'name' => $company['name'],
                'email' => $company['email'],
                'email_verified_at' => now(),
                'password' => bcrypt('password'),
                'role' => 'employer',
            ]);

            $profile = EmployerProfile::create([
                'user_id' => $user->id,
                'business_name' => $company['business_name'],
                'phone' => $company['phone'],
                'city' => $company['city'],
                'province' => $company['province'],
                'address_line_1' => $company['address_line_1'],
                'postal_code' => $company['postal_code'],
                'country' => 'Canada',
                'is_profile_complete' => true,
                'profile_completed_at' => now(),
                'onboarding_step' => 5,
            ]);

            $employers[] = $user;
        }

        // Define 50 job postings (5 per company)
        $jobs = [
            // Metro Clean Services - 5 jobs
            [
                'title' => 'Office Cleaner - Evening Shift',
                'description' => 'Part-time office cleaning position, Monday to Friday 6PM-10PM. Responsibilities include emptying trash, cleaning offices, washrooms, and common areas. Experience preferred but will train.',
                'category' => 'Cleaning & Maintenance',
                'budget' => 22.00,
                'deadline' => now()->addDays(10),
                'required_skills' => ['Office Cleaner', 'Commercial Cleaner', 'Janitor'],
                'location' => 'Toronto, ON',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(1),
            ],
            [
                'title' => 'House Cleaner - Weekly Service',
                'description' => 'Looking for reliable house cleaner for weekly cleaning service. Duties include vacuuming, mopping, dusting, bathroom and kitchen cleaning. Must have own transportation.',
                'category' => 'Cleaning & Maintenance',
                'budget' => 25.00,
                'deadline' => now()->addDays(7),
                'required_skills' => ['House Cleaner', 'Residential Cleaner'],
                'location' => 'Toronto, ON',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(2),
            ],
            [
                'title' => 'Window Cleaner - Commercial Buildings',
                'description' => 'Window cleaning position for commercial buildings. Must be comfortable with heights and have basic equipment. Training provided. Flexible schedule available.',
                'category' => 'Cleaning & Maintenance',
                'budget' => 24.00,
                'deadline' => now()->addDays(12),
                'required_skills' => ['Window Cleaning', 'Commercial Cleaning'],
                'location' => 'Toronto, ON',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subHours(8),
            ],
            [
                'title' => 'Carpet Cleaner - Residential',
                'description' => 'Carpet cleaning technician needed for residential properties. Equipment provided. Must have valid driver\'s license. Great for entry-level position.',
                'category' => 'Cleaning & Maintenance',
                'budget' => 23.00,
                'deadline' => now()->addDays(9),
                'required_skills' => ['Carpet Cleaning', 'Residential Cleaning'],
                'location' => 'Toronto, ON',
                'job_type' => 'contract',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(3),
            ],
            [
                'title' => 'Janitor - Shopping Mall',
                'description' => 'Full-time janitor position at busy shopping mall. Duties include floor maintenance, restroom cleaning, and general upkeep. Benefits available after 90 days.',
                'category' => 'Cleaning & Maintenance',
                'budget' => 21.00,
                'deadline' => now()->addDays(14),
                'required_skills' => ['Janitor', 'Floor Maintenance', 'Commercial Cleaning'],
                'location' => 'Toronto, ON',
                'job_type' => 'full_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(4),
            ],

            // Quick Bite Restaurant Group - 5 jobs
            [
                'title' => 'Line Cook - Fast-Paced Kitchen',
                'description' => 'Busy restaurant seeking line cook for food preparation and cooking. No experience necessary - we will train. Must be able to work in fast-paced environment. Evening shifts available.',
                'category' => 'Food Service',
                'budget' => 22.00,
                'deadline' => now()->addDays(8),
                'required_skills' => ['Line Cook', 'Food Preparation', 'Kitchen Helper'],
                'location' => 'Vancouver, BC',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(2),
            ],
            [
                'title' => 'Server/Waitress - Weekend Shifts',
                'description' => 'Popular family restaurant looking for friendly server for weekend shifts. Experience preferred but will train right candidate. Must have excellent customer service skills and positive attitude.',
                'category' => 'Food Service',
                'budget' => 18.00,
                'deadline' => now()->addDays(6),
                'required_skills' => ['Waiter/Waitress', 'Customer Service'],
                'location' => 'Vancouver, BC',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(1),
            ],
            [
                'title' => 'Dishwasher - Evening Position',
                'description' => 'Dishwasher needed for evening shifts at busy restaurant. Physical work, must be able to stand for long periods. Immediate start available. Team environment.',
                'category' => 'Food Service',
                'budget' => 17.50,
                'deadline' => now()->addDays(5),
                'required_skills' => ['Dishwasher', 'Kitchen Helper'],
                'location' => 'Vancouver, BC',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subHours(12),
            ],
            [
                'title' => 'Cashier - Fast Food Restaurant',
                'description' => 'Cashier position at fast-food restaurant. Must be friendly, handle cash transactions, and work in fast-paced environment. Flexible scheduling available.',
                'category' => 'Food Service',
                'budget' => 16.50,
                'deadline' => now()->addDays(7),
                'required_skills' => ['Cashier', 'Customer Service', 'Cash Handling'],
                'location' => 'Vancouver, BC',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(3),
            ],
            [
                'title' => 'Food Prep Worker - Morning Shift',
                'description' => 'Food prep worker needed for morning shift. Duties include chopping vegetables, preparing ingredients, and kitchen setup. No experience required. Great entry-level position.',
                'category' => 'Food Service',
                'budget' => 19.00,
                'deadline' => now()->addDays(9),
                'required_skills' => ['Food Preparation', 'Kitchen Helper'],
                'location' => 'Vancouver, BC',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(4),
            ],

            // City Express Delivery - 5 jobs
            [
                'title' => 'Delivery Driver - Food Delivery',
                'description' => 'Join our delivery team! Use your own vehicle to deliver food orders. Flexible scheduling, work when you want. Must have valid license, insurance, and smartphone. Tips included.',
                'category' => 'Transportation & Delivery',
                'budget' => 20.00,
                'deadline' => now()->addDays(14),
                'required_skills' => ['Delivery Driver', 'Customer Service'],
                'location' => 'Calgary, AB',
                'job_type' => 'contract',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(3),
            ],
            [
                'title' => 'Courier - Same Day Delivery',
                'description' => 'Independent courier needed for same-day package delivery across the city. Must have reliable vehicle and GPS. Routes provided daily. Immediate start available.',
                'category' => 'Transportation & Delivery',
                'budget' => 22.50,
                'deadline' => now()->addDays(5),
                'required_skills' => ['Courier', 'Same Day Delivery'],
                'location' => 'Calgary, AB',
                'job_type' => 'contract',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(2),
            ],
            [
                'title' => 'Package Handler - Sorting Facility',
                'description' => 'Package handler needed at sorting facility. Duties include loading, unloading, and sorting packages. Physical work, must be able to lift up to 50lbs. Shifts available.',
                'category' => 'Transportation & Delivery',
                'budget' => 19.50,
                'deadline' => now()->addDays(10),
                'required_skills' => ['Package Handler', 'Physical Labor'],
                'location' => 'Calgary, AB',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(1),
            ],
            [
                'title' => 'Moving Helper - Weekend Work',
                'description' => 'Help with residential moves on weekends. Loading, unloading, and packing assistance. Must be physically fit and able to lift heavy items. Great weekend income opportunity.',
                'category' => 'Transportation & Delivery',
                'budget' => 21.00,
                'deadline' => now()->addDays(6),
                'required_skills' => ['Moving Helper', 'Loading/Unloading'],
                'location' => 'Calgary, AB',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subHours(10),
            ],
            [
                'title' => 'Van Driver - Local Deliveries',
                'description' => 'Van driver needed for local delivery routes. Must have clean driving record and valid license. Company vehicle provided. Morning and afternoon shifts available.',
                'category' => 'Transportation & Delivery',
                'budget' => 23.00,
                'deadline' => now()->addDays(11),
                'required_skills' => ['Van Driver', 'Delivery Driver'],
                'location' => 'Calgary, AB',
                'job_type' => 'full_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(4),
            ],

            // Retail Plus Stores - 5 jobs
            [
                'title' => 'Cashier - Part-Time Evenings',
                'description' => 'Part-time cashier position for busy grocery store. Evening shifts available, perfect for students or second job. Customer service experience preferred. Benefits available.',
                'category' => 'Retail',
                'budget' => 17.00,
                'deadline' => now()->addDays(13),
                'required_skills' => ['Cashier', 'Customer Service'],
                'location' => 'Ottawa, ON',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(2),
            ],
            [
                'title' => 'Stock Associate - Weekend Work',
                'description' => 'Weekend stock associate for retail store. Duties include receiving shipments, stocking shelves, and inventory management. Must be able to lift 50lbs. Great for extra income.',
                'category' => 'Retail',
                'budget' => 18.50,
                'deadline' => now()->addDays(10),
                'required_skills' => ['Stock Associate', 'Inventory Management'],
                'location' => 'Ottawa, ON',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(1),
            ],
            [
                'title' => 'Retail Sales Associate - Fashion Store',
                'description' => 'Friendly sales associate needed for fashion retail store. Must be outgoing, help customers find products, and maintain store appearance. Weekend availability required.',
                'category' => 'Retail',
                'budget' => 16.50,
                'deadline' => now()->addDays(8),
                'required_skills' => ['Retail Sales', 'Customer Service'],
                'location' => 'Ottawa, ON',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subHours(8),
            ],
            [
                'title' => 'Store Greeter - Customer Service',
                'description' => 'Store greeter position to welcome customers and assist with directions. Must be friendly and approachable. Perfect for entry-level position. Flexible hours available.',
                'category' => 'Retail',
                'budget' => 16.00,
                'deadline' => now()->addDays(9),
                'required_skills' => ['Customer Service', 'Greeter'],
                'location' => 'Ottawa, ON',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(3),
            ],
            [
                'title' => 'Price Tag Clerk - Pricing Department',
                'description' => 'Price tag clerk needed to update prices and maintain price displays. Attention to detail required. Morning shifts available. Training provided.',
                'category' => 'Retail',
                'budget' => 17.50,
                'deadline' => now()->addDays(12),
                'required_skills' => ['Retail', 'Attention to Detail'],
                'location' => 'Ottawa, ON',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(4),
            ],

            // Fresh Market Grocers - 5 jobs
            [
                'title' => 'Produce Clerk - Grocery Store',
                'description' => 'Produce clerk needed to stock fruits and vegetables, maintain displays, and assist customers. Must be able to lift boxes. Early morning shifts available.',
                'category' => 'Retail',
                'budget' => 18.00,
                'deadline' => now()->addDays(11),
                'required_skills' => ['Produce Clerk', 'Stocking'],
                'location' => 'Montreal, QC',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(2),
            ],
            [
                'title' => 'Meat Department Helper',
                'description' => 'Meat department helper needed for packaging, labeling, and customer service. Food safety training provided. Must be available weekends. Previous experience helpful but not required.',
                'category' => 'Retail',
                'budget' => 19.00,
                'deadline' => now()->addDays(9),
                'required_skills' => ['Meat Department', 'Food Handling'],
                'location' => 'Montreal, QC',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(1),
            ],
            [
                'title' => 'Bakery Assistant - Early Morning',
                'description' => 'Bakery assistant needed for early morning shifts. Help with baking, packaging, and customer service. Must be able to start work early. No experience required, training provided.',
                'category' => 'Retail',
                'budget' => 18.50,
                'deadline' => now()->addDays(7),
                'required_skills' => ['Bakery Assistant', 'Food Preparation'],
                'location' => 'Montreal, QC',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subHours(12),
            ],
            [
                'title' => 'Cart Attendant - Parking Lot',
                'description' => 'Cart attendant needed to collect shopping carts from parking lot and return to store. Physical work, must be comfortable working outdoors. Flexible schedule.',
                'category' => 'Retail',
                'budget' => 16.50,
                'deadline' => now()->addDays(8),
                'required_skills' => ['Cart Attendant', 'Physical Labor'],
                'location' => 'Montreal, QC',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(3),
            ],
            [
                'title' => 'Deli Counter Worker',
                'description' => 'Deli counter worker needed to serve customers, slice meats and cheeses, and maintain clean work area. Customer service skills required. Weekends mandatory.',
                'category' => 'Retail',
                'budget' => 19.50,
                'deadline' => now()->addDays(10),
                'required_skills' => ['Deli Worker', 'Customer Service', 'Food Handling'],
                'location' => 'Montreal, QC',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(4),
            ],

            // Elite Event Services - 5 jobs
            [
                'title' => 'Event Setup Crew - Weddings & Parties',
                'description' => 'Event setup and breakdown crew needed for weddings and private parties. Weekend work, must be reliable and detail-oriented. Experience with tent and equipment setup preferred.',
                'category' => 'Event Services',
                'budget' => 21.00,
                'deadline' => now()->addDays(5),
                'required_skills' => ['Event Setup', 'Team Work'],
                'location' => 'Edmonton, AB',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(2),
            ],
            [
                'title' => 'Parking Attendant - Downtown Events',
                'description' => 'Parking attendant needed for downtown events and venues. Must be friendly, professional, and able to handle cash transactions. Evening and weekend availability required.',
                'category' => 'Event Services',
                'budget' => 18.50,
                'deadline' => now()->addDays(8),
                'required_skills' => ['Customer Service', 'Cash Handling'],
                'location' => 'Edmonton, AB',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(1),
            ],
            [
                'title' => 'Bartender Helper - Event Staff',
                'description' => 'Bartender helper needed for events and parties. Duties include ice preparation, glass washing, and restocking. Must be 18+. Evening and weekend shifts.',
                'category' => 'Event Services',
                'budget' => 20.00,
                'deadline' => now()->addDays(6),
                'required_skills' => ['Event Staff', 'Bar Helper'],
                'location' => 'Edmonton, AB',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subHours(10),
            ],
            [
                'title' => 'Catering Server - Private Events',
                'description' => 'Catering server needed for private events and corporate functions. Must be well-groomed, professional, and able to carry trays. Weekend availability essential.',
                'category' => 'Event Services',
                'budget' => 22.00,
                'deadline' => now()->addDays(9),
                'required_skills' => ['Catering Server', 'Customer Service'],
                'location' => 'Edmonton, AB',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(3),
            ],
            [
                'title' => 'Event Cleanup Crew',
                'description' => 'Event cleanup crew member needed for post-event cleanup and breakdown. Physical work, must be available late evenings. Immediate start available.',
                'category' => 'Event Services',
                'budget' => 19.00,
                'deadline' => now()->addDays(7),
                'required_skills' => ['Event Cleanup', 'Physical Labor'],
                'location' => 'Edmonton, AB',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(4),
            ],

            // Comfort Home Care - 5 jobs
            [
                'title' => 'Home Care Assistant - Elder Care',
                'description' => 'Compassionate home care assistant needed to help elderly client with daily activities, light housekeeping, and companionship. Flexible schedule, background check required.',
                'category' => 'Personal Care',
                'budget' => 24.00,
                'deadline' => now()->addDays(11),
                'required_skills' => ['Personal Care Assistant', 'Elder Care'],
                'location' => 'Winnipeg, MB',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(2),
            ],
            [
                'title' => 'Pet Sitter - Dog Walking Services',
                'description' => 'Reliable pet sitter needed for daily dog walking and pet care services. Must love animals and be available weekdays. References required. Perfect for animal lovers!',
                'category' => 'Personal Care',
                'budget' => 17.00,
                'deadline' => now()->addDays(9),
                'required_skills' => ['Pet Sitting', 'Dog Walking'],
                'location' => 'Winnipeg, MB',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(1),
            ],
            [
                'title' => 'Companion Care - Senior Support',
                'description' => 'Companion care worker needed to provide companionship and light assistance to senior clients. Must be patient, kind, and reliable. Flexible hours, training provided.',
                'category' => 'Personal Care',
                'budget' => 20.00,
                'deadline' => now()->addDays(12),
                'required_skills' => ['Companion Care', 'Senior Care'],
                'location' => 'Winnipeg, MB',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subHours(8),
            ],
            [
                'title' => 'Housekeeping Assistant - Home Care',
                'description' => 'Housekeeping assistant needed for home care clients. Duties include light cleaning, laundry, and meal preparation. Must be trustworthy and reliable. Background check required.',
                'category' => 'Personal Care',
                'budget' => 21.00,
                'deadline' => now()->addDays(10),
                'required_skills' => ['Housekeeping', 'Home Care'],
                'location' => 'Winnipeg, MB',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(3),
            ],
            [
                'title' => 'Respite Care Worker - Flexible Hours',
                'description' => 'Respite care worker needed to provide temporary care for clients, giving family caregivers a break. Flexible scheduling, training provided. Compassionate individuals preferred.',
                'category' => 'Personal Care',
                'budget' => 23.00,
                'deadline' => now()->addDays(13),
                'required_skills' => ['Respite Care', 'Personal Care'],
                'location' => 'Winnipeg, MB',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(4),
            ],

            // Green Lawn Landscaping - 5 jobs
            [
                'title' => 'Lawn Care Specialist - Weekly Service',
                'description' => 'Lawn maintenance for residential properties including mowing, edging, and basic landscaping. Must have transportation for equipment. Regular weekly clients available.',
                'category' => 'Landscaping & Outdoors',
                'budget' => 26.00,
                'deadline' => now()->addDays(7),
                'required_skills' => ['Lawn Care', 'Landscaping'],
                'location' => 'Hamilton, ON',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(2),
            ],
            [
                'title' => 'Garden Maintenance Worker',
                'description' => 'Garden maintenance worker needed for weeding, planting, and general garden upkeep. Must be comfortable working outdoors. Seasonal work with potential for year-round.',
                'category' => 'Landscaping & Outdoors',
                'budget' => 24.00,
                'deadline' => now()->addDays(9),
                'required_skills' => ['Garden Maintenance', 'Landscaping'],
                'location' => 'Hamilton, ON',
                'job_type' => 'contract',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(1),
            ],
            [
                'title' => 'Yard Cleanup Worker - Seasonal',
                'description' => 'Yard cleanup worker needed for fall and spring cleanup jobs. Duties include raking leaves, bagging yard waste, and general cleanup. Physical work, must be able to lift heavy bags.',
                'category' => 'Landscaping & Outdoors',
                'budget' => 22.00,
                'deadline' => now()->addDays(8),
                'required_skills' => ['Yard Cleanup', 'Physical Labor'],
                'location' => 'Hamilton, ON',
                'job_type' => 'contract',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subHours(12),
            ],
            [
                'title' => 'Snow Removal Worker - Winter Contract',
                'description' => 'Snow removal team member for residential and commercial properties. Must be available for early morning calls and have warm weather gear. Seasonal contract with good pay.',
                'category' => 'Seasonal Work',
                'budget' => 25.00,
                'deadline' => now()->addDays(6),
                'required_skills' => ['Snow Removal', 'Physical Labor'],
                'location' => 'Hamilton, ON',
                'job_type' => 'contract',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(3),
            ],
            [
                'title' => 'Hedge Trimmer - Residential Properties',
                'description' => 'Hedge trimming and shrub maintenance worker needed. Must have basic knowledge of plants and be comfortable using hand tools. Training provided for right candidate.',
                'category' => 'Landscaping & Outdoors',
                'budget' => 23.00,
                'deadline' => now()->addDays(10),
                'required_skills' => ['Hedge Trimming', 'Landscaping'],
                'location' => 'Hamilton, ON',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(4),
            ],

            // Speedy Courier Services - 5 jobs
            [
                'title' => 'Bicycle Courier - Downtown Area',
                'description' => 'Bicycle courier needed for downtown delivery routes. Must have own bicycle and be comfortable riding in traffic. Great for active individuals. Flexible hours.',
                'category' => 'Transportation & Delivery',
                'budget' => 19.00,
                'deadline' => now()->addDays(7),
                'required_skills' => ['Bicycle Courier', 'Delivery'],
                'location' => 'Quebec City, QC',
                'job_type' => 'contract',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(2),
            ],
            [
                'title' => 'Package Sorter - Distribution Center',
                'description' => 'Package sorter needed at distribution center. Duties include sorting packages by destination and loading onto trucks. Fast-paced environment, physical work required.',
                'category' => 'Transportation & Delivery',
                'budget' => 20.50,
                'deadline' => now()->addDays(11),
                'required_skills' => ['Package Sorting', 'Physical Labor'],
                'location' => 'Quebec City, QC',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(1),
            ],
            [
                'title' => 'Express Delivery Driver',
                'description' => 'Express delivery driver needed for urgent local deliveries. Must have reliable vehicle and clean driving record. Company phone provided. Flexible scheduling.',
                'category' => 'Transportation & Delivery',
                'budget' => 24.00,
                'deadline' => now()->addDays(9),
                'required_skills' => ['Express Delivery', 'Delivery Driver'],
                'location' => 'Quebec City, QC',
                'job_type' => 'contract',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subHours(10),
            ],
            [
                'title' => 'Mailroom Assistant - Office Building',
                'description' => 'Mailroom assistant needed for office building. Duties include receiving mail, sorting, and distribution. Must be organized and detail-oriented. Morning shifts available.',
                'category' => 'Transportation & Delivery',
                'budget' => 18.00,
                'deadline' => now()->addDays(8),
                'required_skills' => ['Mailroom', 'Organization'],
                'location' => 'Quebec City, QC',
                'job_type' => 'part_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(3),
            ],
            [
                'title' => 'Last-Mile Delivery Driver',
                'description' => 'Last-mile delivery driver for final delivery to customers. Must have SUV or van. GPS navigation provided. Great income potential with tips.',
                'category' => 'Transportation & Delivery',
                'budget' => 22.00,
                'deadline' => now()->addDays(10),
                'required_skills' => ['Last-Mile Delivery', 'Delivery Driver'],
                'location' => 'Quebec City, QC',
                'job_type' => 'contract',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(4),
            ],

            // Warehouse Logistics Inc - 5 jobs
            [
                'title' => 'Warehouse Worker - Day Shift',
                'description' => 'Full-time warehouse position involving receiving, organizing inventory, and order fulfillment. Forklift certification preferred but not required. Benefits after 90 days.',
                'category' => 'Transportation & Delivery',
                'budget' => 21.00,
                'deadline' => now()->addDays(15),
                'required_skills' => ['Warehouse Worker', 'Inventory Management'],
                'location' => 'Mississauga, ON',
                'job_type' => 'full_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(2),
            ],
            [
                'title' => 'Order Picker - Warehouse',
                'description' => 'Order picker needed to pick items from warehouse shelves for shipment. Must be able to lift up to 50lbs and work on feet for extended periods. Training provided.',
                'category' => 'Transportation & Delivery',
                'budget' => 20.00,
                'deadline' => now()->addDays(12),
                'required_skills' => ['Order Picker', 'Warehouse'],
                'location' => 'Mississauga, ON',
                'job_type' => 'full_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(1),
            ],
            [
                'title' => 'Inventory Clerk - Stock Management',
                'description' => 'Inventory clerk needed to count and track warehouse stock. Must be detail-oriented and able to use basic computer systems. Day shifts available.',
                'category' => 'Transportation & Delivery',
                'budget' => 19.50,
                'deadline' => now()->addDays(13),
                'required_skills' => ['Inventory Clerk', 'Stock Management'],
                'location' => 'Mississauga, ON',
                'job_type' => 'full_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subHours(8),
            ],
            [
                'title' => 'Loading Dock Worker',
                'description' => 'Loading dock worker needed to load and unload trucks. Physical work, must be able to lift heavy items. Must be available for morning and afternoon shifts.',
                'category' => 'Transportation & Delivery',
                'budget' => 22.00,
                'deadline' => now()->addDays(11),
                'required_skills' => ['Loading Dock', 'Physical Labor'],
                'location' => 'Mississauga, ON',
                'job_type' => 'full_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(3),
            ],
            [
                'title' => 'General Laborer - Warehouse',
                'description' => 'General laborer needed for various warehouse tasks including cleaning, organizing, and basic maintenance. No experience required. Entry-level position with growth potential.',
                'category' => 'Transportation & Delivery',
                'budget' => 19.00,
                'deadline' => now()->addDays(14),
                'required_skills' => ['General Labor', 'Warehouse'],
                'location' => 'Mississauga, ON',
                'job_type' => 'full_time',
                'experience_level' => 'entry',
                'status' => 'active',
                'published_at' => now()->subDays(4),
            ],
        ];

        // Create jobs and assign to employers (5 jobs per company)
        $jobIndex = 0;
        foreach ($employers as $employer) {
            for ($i = 0; $i < 5; $i++) {
                if ($jobIndex < count($jobs)) {
                    $jobData = $jobs[$jobIndex];
                    Job::create(array_merge($jobData, [
                        'employer_id' => $employer->id,
                        'views_count' => rand(5, 50),
                        'applications_count' => rand(0, 8),
                        'payment_status' => 'pending',
                    ]));
                    $jobIndex++;
                }
            }
        }

        $this->command->info('Successfully created 10 companies and 50 job postings!');
    }
}

