<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class GlobalSkillsSeeder extends Seeder
{
    public function run(): void
    {
        // Clear existing data to prevent duplicates
        if (DB::getDriverName() === 'mysql') {
            DB::statement('SET FOREIGN_KEY_CHECKS=0');
        }
        DB::table('global_skills')->truncate();
        if (DB::getDriverName() === 'mysql') {
            DB::statement('SET FOREIGN_KEY_CHECKS=1');
        }
        
        $now = Carbon::now();
        
        $skills = [
            // Automotive
            ['name' => 'Air Conditioning Repair', 'category' => 'Automotive', 'requires_certification' => false],
            ['name' => 'Auto Body Repair', 'category' => 'Automotive', 'requires_certification' => true],
            ['name' => 'Auto Detailing', 'category' => 'Automotive', 'requires_certification' => false],
            ['name' => 'Auto Electrician', 'category' => 'Automotive', 'requires_certification' => true],
            ['name' => 'Auto Glass Repair', 'category' => 'Automotive', 'requires_certification' => false],
            ['name' => 'Auto Mechanic', 'category' => 'Automotive', 'requires_certification' => true],
            ['name' => 'Auto Painting', 'category' => 'Automotive', 'requires_certification' => true],
            ['name' => 'Brake Specialist', 'category' => 'Automotive', 'requires_certification' => true],
            ['name' => 'Car Detailing', 'category' => 'Automotive', 'requires_certification' => false],
            ['name' => 'Car Washing', 'category' => 'Automotive', 'requires_certification' => false],
            ['name' => 'Diesel Mechanic', 'category' => 'Automotive', 'requires_certification' => true],
            ['name' => 'Engine Repair', 'category' => 'Automotive', 'requires_certification' => true],
            ['name' => 'Exhaust System Repair', 'category' => 'Automotive', 'requires_certification' => false],
            ['name' => 'Mobile Mechanic', 'category' => 'Automotive', 'requires_certification' => true],
            ['name' => 'Motorcycle Mechanic', 'category' => 'Automotive', 'requires_certification' => true],
            ['name' => 'Oil Change Technician', 'category' => 'Automotive', 'requires_certification' => false],
            ['name' => 'Tire Installation', 'category' => 'Automotive', 'requires_certification' => false],
            ['name' => 'Tire Repair', 'category' => 'Automotive', 'requires_certification' => false],
            ['name' => 'Tire Service', 'category' => 'Automotive', 'requires_certification' => false],
            ['name' => 'Transmission Repair', 'category' => 'Automotive', 'requires_certification' => true],
            ['name' => 'Vehicle Inspector', 'category' => 'Automotive', 'requires_certification' => true],
            ['name' => 'Vehicle Wrap Installer', 'category' => 'Automotive', 'requires_certification' => false],
            ['name' => 'Wheel Alignment', 'category' => 'Automotive', 'requires_certification' => false],

            // Cleaning & Maintenance
            ['name' => 'Biohazard Cleaning', 'category' => 'Cleaning & Maintenance', 'requires_certification' => true],
            ['name' => 'Blind Cleaning', 'category' => 'Cleaning & Maintenance', 'requires_certification' => false],
            ['name' => 'Carpet Cleaner', 'category' => 'Cleaning & Maintenance', 'requires_certification' => false],
            ['name' => 'Chimney Sweep', 'category' => 'Cleaning & Maintenance', 'requires_certification' => true],
            ['name' => 'Commercial Cleaner', 'category' => 'Cleaning & Maintenance', 'requires_certification' => false],
            ['name' => 'Construction Cleanup', 'category' => 'Cleaning & Maintenance', 'requires_certification' => false],
            ['name' => 'Deep Cleaning Specialist', 'category' => 'Cleaning & Maintenance', 'requires_certification' => false],
            ['name' => 'Disinfection Specialist', 'category' => 'Cleaning & Maintenance', 'requires_certification' => true],
            ['name' => 'Drain Cleaning', 'category' => 'Cleaning & Maintenance', 'requires_certification' => false],
            ['name' => 'Driveway Cleaning', 'category' => 'Cleaning & Maintenance', 'requires_certification' => false],
            ['name' => 'Duct Cleaning', 'category' => 'Cleaning & Maintenance', 'requires_certification' => true],
            ['name' => 'Graffiti Removal', 'category' => 'Cleaning & Maintenance', 'requires_certification' => false],
            ['name' => 'Grout Cleaning', 'category' => 'Cleaning & Maintenance', 'requires_certification' => false],
            ['name' => 'Gutter Cleaning', 'category' => 'Cleaning & Maintenance', 'requires_certification' => false],
            ['name' => 'Hoarding Cleanup', 'category' => 'Cleaning & Maintenance', 'requires_certification' => false],
            ['name' => 'Hospital Cleaner', 'category' => 'Cleaning & Maintenance', 'requires_certification' => true],
            ['name' => 'House Cleaner', 'category' => 'Cleaning & Maintenance', 'requires_certification' => false],
            ['name' => 'Industrial Cleaner', 'category' => 'Cleaning & Maintenance', 'requires_certification' => true],
            ['name' => 'Janitor', 'category' => 'Cleaning & Maintenance', 'requires_certification' => false],
            ['name' => 'Kitchen Deep Clean', 'category' => 'Cleaning & Maintenance', 'requires_certification' => false],
            ['name' => 'Maid Service', 'category' => 'Cleaning & Maintenance', 'requires_certification' => false],
            ['name' => 'Mold Remediation', 'category' => 'Cleaning & Maintenance', 'requires_certification' => true],
            ['name' => 'Move-Out Cleaning', 'category' => 'Cleaning & Maintenance', 'requires_certification' => false],
            ['name' => 'Office Cleaner', 'category' => 'Cleaning & Maintenance', 'requires_certification' => false],
            ['name' => 'Post-Construction Cleaning', 'category' => 'Cleaning & Maintenance', 'requires_certification' => false],
            ['name' => 'Power Washing', 'category' => 'Cleaning & Maintenance', 'requires_certification' => false],
            ['name' => 'Pressure Washing', 'category' => 'Cleaning & Maintenance', 'requires_certification' => false],
            ['name' => 'Residential Cleaner', 'category' => 'Cleaning & Maintenance', 'requires_certification' => false],
            ['name' => 'Restaurant Cleaner', 'category' => 'Cleaning & Maintenance', 'requires_certification' => false],
            ['name' => 'Roof Cleaning', 'category' => 'Cleaning & Maintenance', 'requires_certification' => false],
            ['name' => 'Sanitization Specialist', 'category' => 'Cleaning & Maintenance', 'requires_certification' => true],
            ['name' => 'School Cleaner', 'category' => 'Cleaning & Maintenance', 'requires_certification' => false],
            ['name' => 'Siding Cleaning', 'category' => 'Cleaning & Maintenance', 'requires_certification' => false],
            ['name' => 'Steam Cleaning', 'category' => 'Cleaning & Maintenance', 'requires_certification' => false],
            ['name' => 'Tile Cleaning', 'category' => 'Cleaning & Maintenance', 'requires_certification' => false],
            ['name' => 'Upholstery Cleaning', 'category' => 'Cleaning & Maintenance', 'requires_certification' => false],
            ['name' => 'Vacation Rental Cleaner', 'category' => 'Cleaning & Maintenance', 'requires_certification' => false],
            ['name' => 'Window Cleaner', 'category' => 'Cleaning & Maintenance', 'requires_certification' => false],

            // Event Services
            ['name' => 'Audio Visual Technician', 'category' => 'Event Services', 'requires_certification' => false],
            ['name' => 'Balloon Artist', 'category' => 'Event Services', 'requires_certification' => false],
            ['name' => 'Banquet Server', 'category' => 'Event Services', 'requires_certification' => true],
            ['name' => 'Bartender', 'category' => 'Event Services', 'requires_certification' => true],
            ['name' => 'Bouncer', 'category' => 'Event Services', 'requires_certification' => true],
            ['name' => 'Caricature Artist', 'category' => 'Event Services', 'requires_certification' => false],
            ['name' => 'Caterer', 'category' => 'Event Services', 'requires_certification' => true],
            ['name' => 'Clown', 'category' => 'Event Services', 'requires_certification' => false],
            ['name' => 'Coat Check Attendant', 'category' => 'Event Services', 'requires_certification' => false],
            ['name' => 'DJ', 'category' => 'Event Services', 'requires_certification' => false],
            ['name' => 'Emcee', 'category' => 'Event Services', 'requires_certification' => false],
            ['name' => 'Event Bartender', 'category' => 'Event Services', 'requires_certification' => true],
            ['name' => 'Event Coordinator', 'category' => 'Event Services', 'requires_certification' => false],
            ['name' => 'Event Decorator', 'category' => 'Event Services', 'requires_certification' => false],
            ['name' => 'Event Photographer', 'category' => 'Event Services', 'requires_certification' => false],
            ['name' => 'Event Security', 'category' => 'Event Services', 'requires_certification' => true],
            ['name' => 'Event Server', 'category' => 'Event Services', 'requires_certification' => true],
            ['name' => 'Event Setup', 'category' => 'Event Services', 'requires_certification' => false],
            ['name' => 'Event Teardown', 'category' => 'Event Services', 'requires_certification' => false],
            ['name' => 'Event Videographer', 'category' => 'Event Services', 'requires_certification' => false],
            ['name' => 'Face Painter', 'category' => 'Event Services', 'requires_certification' => false],
            ['name' => 'Lighting Technician', 'category' => 'Event Services', 'requires_certification' => false],
            ['name' => 'Magician', 'category' => 'Event Services', 'requires_certification' => false],
            ['name' => 'Mixologist', 'category' => 'Event Services', 'requires_certification' => true],
            ['name' => 'Musician', 'category' => 'Event Services', 'requires_certification' => false],
            ['name' => 'Party Host', 'category' => 'Event Services', 'requires_certification' => false],
            ['name' => 'Photographer', 'category' => 'Event Services', 'requires_certification' => false],
            ['name' => 'Photo Booth Operator', 'category' => 'Event Services', 'requires_certification' => false],
            ['name' => 'Sound Engineer', 'category' => 'Event Services', 'requires_certification' => false],
            ['name' => 'Stage Manager', 'category' => 'Event Services', 'requires_certification' => false],
            ['name' => 'Usher', 'category' => 'Event Services', 'requires_certification' => false],
            ['name' => 'Valet Attendant', 'category' => 'Event Services', 'requires_certification' => false],
            ['name' => 'Vendor Coordinator', 'category' => 'Event Services', 'requires_certification' => false],
            ['name' => 'Wedding Coordinator', 'category' => 'Event Services', 'requires_certification' => false],

            // Food Service
            ['name' => 'Bagger', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Baker', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Bakery Assistant', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Banquet Chef', 'category' => 'Food Service', 'requires_certification' => true],
            ['name' => 'Barback', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Barista', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Bartender', 'category' => 'Food Service', 'requires_certification' => true],
            ['name' => 'BBQ Pitmaster', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Beverage Cart Attendant', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Bread Baker', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Breakfast Cook', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Buffet Attendant', 'category' => 'Food Service', 'requires_certification' => true],
            ['name' => 'Busser', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Butcher', 'category' => 'Food Service', 'requires_certification' => true],
            ['name' => 'Cafeteria Worker', 'category' => 'Food Service', 'requires_certification' => true],
            ['name' => 'Cake Decorator', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Candy Maker', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Cashier', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Catering Assistant', 'category' => 'Food Service', 'requires_certification' => true],
            ['name' => 'Catering Chef', 'category' => 'Food Service', 'requires_certification' => true],
            ['name' => 'Catering Server', 'category' => 'Food Service', 'requires_certification' => true],
            ['name' => 'Chef de Cuisine', 'category' => 'Food Service', 'requires_certification' => true],
            ['name' => 'Chef de Partie', 'category' => 'Food Service', 'requires_certification' => true],
            ['name' => 'Chocolatier', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Coffee Roaster', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Coffee Shop Manager', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Commis Chef', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Delivery Driver', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Deli Clerk', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Dessert Chef', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Dishwasher', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Drive-Thru Attendant', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Executive Chef', 'category' => 'Food Service', 'requires_certification' => true],
            ['name' => 'Expeditor', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Fast Food Worker', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Fish Cutter', 'category' => 'Food Service', 'requires_certification' => true],
            ['name' => 'Food Assembler', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Food Counter Attendant', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Food Handler', 'category' => 'Food Service', 'requires_certification' => true],
            ['name' => 'Food Preparer', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Food Runner', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Food Safety Inspector', 'category' => 'Food Service', 'requires_certification' => true],
            ['name' => 'Food Server', 'category' => 'Food Service', 'requires_certification' => true],
            ['name' => 'Food Stylist', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Food Truck Operator', 'category' => 'Food Service', 'requires_certification' => true],
            ['name' => 'Fry Cook', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Garde Manger', 'category' => 'Food Service', 'requires_certification' => true],
            ['name' => 'Grill Cook', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Head Chef', 'category' => 'Food Service', 'requires_certification' => true],
            ['name' => 'Host/Hostess', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Ice Cream Maker', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Kitchen Assistant', 'category' => 'Food Service', 'requires_certification' => true],
            ['name' => 'Kitchen Helper', 'category' => 'Food Service', 'requires_certification' => true],
            ['name' => 'Kitchen Manager', 'category' => 'Food Service', 'requires_certification' => true],
            ['name' => 'Kitchen Porter', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Line Cook', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Meat Cutter', 'category' => 'Food Service', 'requires_certification' => true],
            ['name' => 'Night Baker', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Pantry Cook', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Pastry Assistant', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Pastry Chef', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Personal Chef', 'category' => 'Food Service', 'requires_certification' => true],
            ['name' => 'Pizza Cook', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Pizza Delivery Driver', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Pizza Maker', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Prep Cook', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Private Chef', 'category' => 'Food Service', 'requires_certification' => true],
            ['name' => 'Restaurant Manager', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Salad Bar Attendant', 'category' => 'Food Service', 'requires_certification' => true],
            ['name' => 'Sandwich Artist', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Saucier', 'category' => 'Food Service', 'requires_certification' => true],
            ['name' => 'Short Order Cook', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Sommelier', 'category' => 'Food Service', 'requires_certification' => true],
            ['name' => 'Sous Chef', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Sushi Chef', 'category' => 'Food Service', 'requires_certification' => true],
            ['name' => 'Tea Specialist', 'category' => 'Food Service', 'requires_certification' => false],
            ['name' => 'Waiter/Waitress', 'category' => 'Food Service', 'requires_certification' => true],
            ['name' => 'Wine Steward', 'category' => 'Food Service', 'requires_certification' => true],

            // Landscaping & Outdoors
            ['name' => 'Arborist', 'category' => 'Landscaping & Outdoors', 'requires_certification' => true],
            ['name' => 'Christmas Light Installer', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],
            ['name' => 'Deck Builder', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],
            ['name' => 'Deck Staining', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],
            ['name' => 'Drainage Specialist', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],
            ['name' => 'Fence Builder', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],
            ['name' => 'Fence Repair', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],
            ['name' => 'Fertilization Specialist', 'category' => 'Landscaping & Outdoors', 'requires_certification' => true],
            ['name' => 'Gardener', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],
            ['name' => 'Hardscape Installer', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],
            ['name' => 'Hedge Trimming', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],
            ['name' => 'Irrigation Specialist', 'category' => 'Landscaping & Outdoors', 'requires_certification' => true],
            ['name' => 'Landscape Architect', 'category' => 'Landscaping & Outdoors', 'requires_certification' => true],
            ['name' => 'Landscape Designer', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],
            ['name' => 'Landscaper', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],
            ['name' => 'Lawn Aeration', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],
            ['name' => 'Lawn Care', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],
            ['name' => 'Lawn Fertilization', 'category' => 'Landscaping & Outdoors', 'requires_certification' => true],
            ['name' => 'Lawn Mowing', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],
            ['name' => 'Lawn Seeding', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],
            ['name' => 'Leaf Removal', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],
            ['name' => 'Mulching', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],
            ['name' => 'Outdoor Lighting Installer', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],
            ['name' => 'Patio Builder', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],
            ['name' => 'Paver Installer', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],
            ['name' => 'Pergola Builder', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],
            ['name' => 'Pest Control', 'category' => 'Landscaping & Outdoors', 'requires_certification' => true],
            ['name' => 'Pond Installation', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],
            ['name' => 'Pool Cleaner', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],
            ['name' => 'Pool Maintenance', 'category' => 'Landscaping & Outdoors', 'requires_certification' => true],
            ['name' => 'Pool Repair', 'category' => 'Landscaping & Outdoors', 'requires_certification' => true],
            ['name' => 'Pressure Washing', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],
            ['name' => 'Pruning Specialist', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],
            ['name' => 'Retaining Wall Builder', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],
            ['name' => 'Sod Installation', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],
            ['name' => 'Snow Plowing', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],
            ['name' => 'Snow Removal', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],
            ['name' => 'Sprinkler Installation', 'category' => 'Landscaping & Outdoors', 'requires_certification' => true],
            ['name' => 'Sprinkler Repair', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],
            ['name' => 'Stump Grinding', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],
            ['name' => 'Tree Planting', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],
            ['name' => 'Tree Removal', 'category' => 'Landscaping & Outdoors', 'requires_certification' => true],
            ['name' => 'Tree Service', 'category' => 'Landscaping & Outdoors', 'requires_certification' => true],
            ['name' => 'Tree Trimming', 'category' => 'Landscaping & Outdoors', 'requires_certification' => true],
            ['name' => 'Weed Control', 'category' => 'Landscaping & Outdoors', 'requires_certification' => true],
            ['name' => 'Xeriscaping', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],
            ['name' => 'Yard Cleanup', 'category' => 'Landscaping & Outdoors', 'requires_certification' => false],

            // Personal Care
            ['name' => 'Acne Specialist', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Acupuncturist', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Aromatherapist', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Barber', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Beauty Consultant', 'category' => 'Personal Care', 'requires_certification' => false],
            ['name' => 'Beauty Therapist', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Body Piercer', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Body Waxing Specialist', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Botox Specialist', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Brow Artist', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Chiropractor', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Color Specialist', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Cosmetic Tattoo Artist', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Cosmetologist', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Electrologist', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Esthetician', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Eyelash Extension Specialist', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Eyebrow Threading', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Facial Specialist', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Hair Colorist', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Hair Extensions Specialist', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Hair Stylist', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Henna Artist', 'category' => 'Personal Care', 'requires_certification' => false],
            ['name' => 'Laser Hair Removal', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Lash Artist', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Makeup Artist', 'category' => 'Personal Care', 'requires_certification' => false],
            ['name' => 'Manicurist', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Massage Therapist', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Medical Esthetician', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Microblading Artist', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Nail Artist', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Nail Technician', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Pedicurist', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Permanent Makeup Artist', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Reflexologist', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Reiki Practitioner', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Salon Assistant', 'category' => 'Personal Care', 'requires_certification' => false],
            ['name' => 'Shampooer', 'category' => 'Personal Care', 'requires_certification' => false],
            ['name' => 'Skin Care Specialist', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Spa Manager', 'category' => 'Personal Care', 'requires_certification' => false],
            ['name' => 'Spa Receptionist', 'category' => 'Personal Care', 'requires_certification' => false],
            ['name' => 'Spa Therapist', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Sports Massage Therapist', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Spray Tan Technician', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Tattoo Artist', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Tattoo Removal Specialist', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Threading Specialist', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Trichologist', 'category' => 'Personal Care', 'requires_certification' => true],
            ['name' => 'Waxing Specialist', 'category' => 'Personal Care', 'requires_certification' => true],

            // Personal Services
            ['name' => 'Babysitter', 'category' => 'Personal Services', 'requires_certification' => true],
            ['name' => 'Caregiver', 'category' => 'Personal Services', 'requires_certification' => true],
            ['name' => 'Dog Groomer', 'category' => 'Personal Services', 'requires_certification' => false],
            ['name' => 'Dog Trainer', 'category' => 'Personal Services', 'requires_certification' => false],
            ['name' => 'Dog Walker', 'category' => 'Personal Services', 'requires_certification' => false],
            ['name' => 'Elder Care', 'category' => 'Personal Services', 'requires_certification' => true],
            ['name' => 'Elderly Companion', 'category' => 'Personal Services', 'requires_certification' => true],
            ['name' => 'Errand Runner', 'category' => 'Personal Services', 'requires_certification' => false],
            ['name' => 'Home Health Aide', 'category' => 'Personal Services', 'requires_certification' => true],
            ['name' => 'House Sitter', 'category' => 'Personal Services', 'requires_certification' => false],
            ['name' => 'Laundry Service', 'category' => 'Personal Services', 'requires_certification' => false],
            ['name' => 'Life Coach', 'category' => 'Personal Services', 'requires_certification' => false],
            ['name' => 'Meal Prep Service', 'category' => 'Personal Services', 'requires_certification' => true],
            ['name' => 'Mobile Notary', 'category' => 'Personal Services', 'requires_certification' => true],
            ['name' => 'Nanny', 'category' => 'Personal Services', 'requires_certification' => true],
            ['name' => 'Organization Specialist', 'category' => 'Personal Services', 'requires_certification' => false],
            ['name' => 'Personal Assistant', 'category' => 'Personal Services', 'requires_certification' => false],
            ['name' => 'Personal Organizer', 'category' => 'Personal Services', 'requires_certification' => false],
            ['name' => 'Personal Shopper', 'category' => 'Personal Services', 'requires_certification' => false],
            ['name' => 'Personal Trainer', 'category' => 'Personal Services', 'requires_certification' => true],
            ['name' => 'Pet Boarding', 'category' => 'Personal Services', 'requires_certification' => false],
            ['name' => 'Pet Sitter', 'category' => 'Personal Services', 'requires_certification' => false],
            ['name' => 'Pet Taxi', 'category' => 'Personal Services', 'requires_certification' => false],
            ['name' => 'Pet Walker', 'category' => 'Personal Services', 'requires_certification' => false],
            ['name' => 'Professional Organizer', 'category' => 'Personal Services', 'requires_certification' => false],
            ['name' => 'Senior Companion', 'category' => 'Personal Services', 'requires_certification' => true],
            ['name' => 'Special Needs Caregiver', 'category' => 'Personal Services', 'requires_certification' => true],
            ['name' => 'Tutor', 'category' => 'Personal Services', 'requires_certification' => false],
            ['name' => 'Yoga Instructor', 'category' => 'Personal Services', 'requires_certification' => true],

            // Technology
            ['name' => 'App Developer', 'category' => 'Technology', 'requires_certification' => false],
            ['name' => 'Audio Equipment Setup', 'category' => 'Technology', 'requires_certification' => false],
            ['name' => 'Computer Repair', 'category' => 'Technology', 'requires_certification' => false],
            ['name' => 'Computer Setup', 'category' => 'Technology', 'requires_certification' => false],
            ['name' => 'Data Recovery', 'category' => 'Technology', 'requires_certification' => false],
            ['name' => 'Game Console Repair', 'category' => 'Technology', 'requires_certification' => false],
            ['name' => 'Gaming PC Builder', 'category' => 'Technology', 'requires_certification' => false],
            ['name' => 'Hardware Installation', 'category' => 'Technology', 'requires_certification' => false],
            ['name' => 'Home Automation', 'category' => 'Technology', 'requires_certification' => false],
            ['name' => 'Home Network Setup', 'category' => 'Technology', 'requires_certification' => false],
            ['name' => 'Home Theater Installation', 'category' => 'Technology', 'requires_certification' => false],
            ['name' => 'IT Support', 'category' => 'Technology', 'requires_certification' => false],
            ['name' => 'Laptop Repair', 'category' => 'Technology', 'requires_certification' => false],
            ['name' => 'Network Installation', 'category' => 'Technology', 'requires_certification' => false],
            ['name' => 'Network Security', 'category' => 'Technology', 'requires_certification' => true],
            ['name' => 'Phone Repair', 'category' => 'Technology', 'requires_certification' => false],
            ['name' => 'Printer Repair', 'category' => 'Technology', 'requires_certification' => false],
            ['name' => 'Security Camera Installation', 'category' => 'Technology', 'requires_certification' => false],
            ['name' => 'Smart Home Installation', 'category' => 'Technology', 'requires_certification' => false],
            ['name' => 'Software Installation', 'category' => 'Technology', 'requires_certification' => false],
            ['name' => 'Sound System Installation', 'category' => 'Technology', 'requires_certification' => false],
            ['name' => 'Tablet Repair', 'category' => 'Technology', 'requires_certification' => false],
            ['name' => 'Tech Support', 'category' => 'Technology', 'requires_certification' => false],
            ['name' => 'TV Installation', 'category' => 'Technology', 'requires_certification' => false],
            ['name' => 'TV Mounting', 'category' => 'Technology', 'requires_certification' => false],
            ['name' => 'TV Repair', 'category' => 'Technology', 'requires_certification' => false],
            ['name' => 'Virus Removal', 'category' => 'Technology', 'requires_certification' => false],
            ['name' => 'Web Design', 'category' => 'Technology', 'requires_certification' => false],
            ['name' => 'Web Development', 'category' => 'Technology', 'requires_certification' => false],
            ['name' => 'WiFi Installation', 'category' => 'Technology', 'requires_certification' => false],

            // Trades & Maintenance
            ['name' => 'Air Duct Cleaning', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Appliance Installation', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Appliance Repair', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Asbestos Removal', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Basement Finishing', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Basement Waterproofing', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Bathroom Remodeling', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Boiler Repair', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Brick Mason', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Cabinet Installation', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Cabinet Maker', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Carpenter', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Carpet Installation', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Ceiling Fan Installation', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Closet Organizer', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Concrete Contractor', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Construction Worker', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Countertop Installation', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Deck Builder', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Demolition', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Door Installation', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Door Repair', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Drain Cleaning', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Drywall Installation', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Drywall Repair', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Duct Work', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Electrical Panel Upgrade', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Electrician', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Faucet Repair', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Fence Installation', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Fire Damage Restoration', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Fireplace Installation', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Fireplace Repair', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Flooring Installation', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Flooring Installer', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Flooring Refinishing', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Furnace Installation', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Furnace Repair', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Garage Door Installation', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Garage Door Repair', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Gas Line Installation', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'General Contractor', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Glass Installer', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Glazier', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Grout Repair', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Handyman', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Hardwood Floor Installation', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Hardwood Floor Refinishing', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Home Inspector', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Home Remodeling', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Hot Tub Repair', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'HVAC Installation', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'HVAC Technician', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Insulation Installation', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Interior Designer', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Kitchen Remodeling', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Laminate Flooring', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Leak Detection', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Light Fixture Installation', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Locksmith', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Masonry', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Mold Inspection', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Outlet Installation', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Painter', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Painting Contractor', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Patio Installation', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Pest Control', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Pipe Repair', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Plastering', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Plumber', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Plumbing Installation', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Pressure Washing', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Refrigeration Technician', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Roof Inspection', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Roof Repair', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Roofer', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Roofing Contractor', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Screen Door Installation', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Septic Tank Service', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Sewer Line Repair', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Shelving Installation', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Shower Installation', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Siding Installation', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Skylight Installation', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Solar Panel Installation', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Stucco Repair', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Sump Pump Installation', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Tile Installation', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Tile Repair', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Toilet Installation', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Toilet Repair', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Wallpaper Installation', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Wallpaper Removal', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Water Damage Restoration', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Water Heater Installation', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Water Heater Repair', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Waterproofing', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Welder', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Well Drilling', 'category' => 'Trades & Maintenance', 'requires_certification' => true],
            ['name' => 'Window Installation', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Window Repair', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Window Replacement', 'category' => 'Trades & Maintenance', 'requires_certification' => false],
            ['name' => 'Wood Floor Repair', 'category' => 'Trades & Maintenance', 'requires_certification' => false],

            // Transportation & Delivery
            ['name' => 'Airport Shuttle', 'category' => 'Transportation & Delivery', 'requires_certification' => false],
            ['name' => 'Bicycle Delivery', 'category' => 'Transportation & Delivery', 'requires_certification' => false],
            ['name' => 'Car Service', 'category' => 'Transportation & Delivery', 'requires_certification' => false],
            ['name' => 'Courier', 'category' => 'Transportation & Delivery', 'requires_certification' => false],
            ['name' => 'Delivery Driver', 'category' => 'Transportation & Delivery', 'requires_certification' => false],
            ['name' => 'Furniture Assembly', 'category' => 'Transportation & Delivery', 'requires_certification' => false],
            ['name' => 'Furniture Delivery', 'category' => 'Transportation & Delivery', 'requires_certification' => false],
            ['name' => 'Furniture Moving', 'category' => 'Transportation & Delivery', 'requires_certification' => false],
            ['name' => 'Heavy Equipment Operator', 'category' => 'Transportation & Delivery', 'requires_certification' => true],
            ['name' => 'Junk Removal', 'category' => 'Transportation & Delivery', 'requires_certification' => false],
            ['name' => 'Limousine Driver', 'category' => 'Transportation & Delivery', 'requires_certification' => false],
            ['name' => 'Loading/Unloading', 'category' => 'Transportation & Delivery', 'requires_certification' => false],
            ['name' => 'Long Distance Mover', 'category' => 'Transportation & Delivery', 'requires_certification' => false],
            ['name' => 'Moving Helper', 'category' => 'Transportation & Delivery', 'requires_certification' => false],
            ['name' => 'Packing Services', 'category' => 'Transportation & Delivery', 'requires_certification' => false],
            ['name' => 'Piano Moving', 'category' => 'Transportation & Delivery', 'requires_certification' => false],
            ['name' => 'Rideshare Driver', 'category' => 'Transportation & Delivery', 'requires_certification' => false],
            ['name' => 'Same Day Delivery', 'category' => 'Transportation & Delivery', 'requires_certification' => false],
            ['name' => 'Storage Services', 'category' => 'Transportation & Delivery', 'requires_certification' => false],
            ['name' => 'Taxi Driver', 'category' => 'Transportation & Delivery', 'requires_certification' => false],
            ['name' => 'Tow Truck Driver', 'category' => 'Transportation & Delivery', 'requires_certification' => true],
            ['name' => 'Truck Driver', 'category' => 'Transportation & Delivery', 'requires_certification' => true],
            ['name' => 'Warehouse Worker', 'category' => 'Transportation & Delivery', 'requires_certification' => false],
        ];

        // Sort skills alphabetically by name
        usort($skills, function($a, $b) {
            return strcmp($a['name'], $b['name']);
        });

        // Use updateOrInsert to prevent duplicates when seeder runs multiple times
        foreach ($skills as $index => $skill) {
            DB::table('global_skills')->updateOrInsert(
                ['name' => $skill['name'], 'category' => $skill['category']],
                [
                    'description' => $skill['description'] ?? null,
                    'requires_certification' => $skill['requires_certification'],
                    'is_active' => true,
                    'sort_order' => $index + 1,
                    'created_at' => $now,
                    'updated_at' => $now,
                ]
            );
        }
    }
}


